# RSS Translator Configuration
translator:
  description_length: 500
  target_language: 'en'
  sleep_time: 1

logging:
  log_directory: 'log'
  log_level: 'DEBUG'
  log_format: '%(asctime)s - %(levelname)s - %(message)s'
  max_bytes: 10485760  # 10MB
  backup_count: 5      # Keep 5 backup files

paths:
  data_directory: 'data'
  output_file: 'translated_feeds.json'
  feed_urls: 'url.md'

threading:
  max_workers: 3
  process_timeout: 120

feed_processing:
  max_age_days: 1
  request_timeout: 45
  max_retries: 3
  retry_delay: 5
  verify_ssl: true
  debug_mode: true
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

output:
  json_indent: 2
