# RSS Translator Configuration
translator:
  entries_limit: 5
  description_length: 200
  target_language: 'en'
  sleep_time: 1

logging:
  log_directory: 'log'
  log_level: 'INFO'
  log_format: '%(asctime)s - %(levelname)s - %(message)s'

paths:
  data_directory: 'data'
  output_file: 'translated_feeds.json'
  feed_urls: 'url.md' 