# RSS Translator Configuration
translator:
  description_length: 500
  target_language: 'en'
  sleep_time: 1

logging:
  log_directory: 'log'
  log_level: 'ERROR'
  log_format: '%(levelname)s - %(message)s'
  max_bytes: 10485760  # 10MB
  backup_count: 5      # Keep 5 backup files

paths:
  data_directory: 'data'
  output_file: 'translated_feeds.json'
  feed_urls: 'url.md'

threading:
  max_workers: 5
  process_timeout: 60  # Seconds

feed_processing:
  max_age_days: 1  # Maximum age of entries to process in days
  request_timeout: 30  # Seconds
  max_retries: 3

output:
  json_indent: 2