name: RSS Translator

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours
  workflow_dispatch:        # Manual trigger
  push:                    # Add push trigger
    branches:
      - main              # Specify branch (change to your main branch name if different)
    paths:                # Only trigger on specific file changes
      - 'translate.py'
      - 'config.yaml'
      - 'url.md'
      - 'requirements.txt'
      - '.github/workflows/**'

jobs:
  translate:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create directories
      run: |
        mkdir -p data
        mkdir -p log
        touch data/.gitkeep
        touch log/.gitkeep
    
    - name: Run translator
      run: |
        # Ensure log directory exists and is writable
        mkdir -p log
        chmod 777 log
        
        for i in {1..3}; do
          python -u translate.py 2>&1 | tee log/runtime.log && break || {
            if [[ $i == 3 ]]; then
              echo "Failed after 3 attempts!"
              exit 1
            fi
            echo "Attempt $i failed! Retrying in 30 seconds..."
            sleep 30
          }
        done
      env:
        PYTHONUNBUFFERED: 1
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -f data/translated_feeds.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update translated feeds"
          git push
        fi 
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: rss-translator-logs
        path: |
          log/*.log*
          log/runtime.log
        retention-days: 7